[package]
name = "gears-examples"
version = "0.1.0"
authors = ["Overpeek <overpeek.fin@gmail.com>"]
edition = "2018"

[[bin]]
name = "gear"
path = "gear/main.rs"

[[bin]]
name = "voxel"
path = "voxel/main.rs"

[dependencies]
# noise = "0.7.0"
# rayon = "1.5.0"

simdnoise = "~3.1"
log = "~0.4"
rand = "~0.8"
cgmath = { version = "~0.18", features = ["swizzle"] }
env_logger = "~0.8"
parking_lot = "~0.11"
gears = { path = "../gears", features = [ "short_namespaces", "validation_panic" ] }
gears-pipeline = { path = "../gears-pipeline" }
gears-traits = { path = "../gears-traits/" }