[package]
name = "gears-examples"
version = "0.1.0"
authors = ["Overpeek <overpeek.fin@gmail.com>"]
edition = "2018"

[[bin]]
name = "main"
path = "main/main.rs"

[features]
default = []
metal = ["gears/metal"]
gl = ["gears/gl"]
dx11 = ["gears/dx11"]
dx12 = ["gears/dx12"]
vulkan = ["gears/vulkan"]

[dependencies]
gears = { path = "../gears" }

[target.'cfg(target_arch = "wasm32")'.dependencies]
log = "0.4"
wasm-bindgen = "0.2.71"
console_error_panic_hook = "0.1.6"
wasm-logger = "0.2.0"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
env_logger = "0.8"